### ISSUE TITLE
less

### ISSUE THREAD

**Issue by HuXin957** [guokaigdg/react-enterprise-template#4]
import styles from './index.less'    className={styles.main} 请教大佬，这种写法现在less不支持了吗

**Comment by guokaigdg** [comment]
> import styles from './index.less' className={styles.main} 请教大佬，这种写法现在less不支持了吗

目前项目不支持 less + CSS Modules  稍后补充支持。👌🏻  


已添加 [feat: ⚡支持less + css modules 模式](https://github.com/guokaigdg/react-enterprise-template/commit/74ecd18161bce9fa44ee916af63669f1114d7c9f)
